#!/bin/bash
## Bash Script to clear cached memory on (Ubuntu/Debian) Linux
## By mrprohack and tamilanmkv
## see <http://blog.philippklaus.de/2011/02/clear-cached-memory-on-ubuntu/>

# Define color codes
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m' # No Color

# Check if bc is installed
if ! command -v bc &> /dev/null; then
    echo -e "${RED}bc tool is not installed. Please install it before running this script.${NC}"
    exit 1
fi

# Get Memory Information
free_mem_before=$(awk '/^MemFree:/ {print $2}' /proc/meminfo | awk '{print $1/1024}')
cached_mem_before=$(awk '/^Cached:/ {print $2}' /proc/meminfo | awk '{print $1/1024}')

# Output Information
echo -e "${YELLOW}This script will clear cached memory and free up your RAM.${NC}\n\nAt the moment you have ${GREEN}$cached_mem_before MiB${NC} cached and ${GREEN}$free_mem_before MiB${NC} free memory."

# Test sync
if ! sync; then
  echo -e "${RED}Something went wrong, It's impossible to sync the filesystem.${NC}"
  exit 1
fi

# Clear Filesystem Buffer using "sync" and Clear Caches
if ! echo 3 > /proc/sys/vm/drop_caches; then
  echo -e "${RED}Something went wrong, It's impossible to clear the caches.${NC}"
  exit 1
fi

free_mem_after=$(awk '/^MemFree:/ {print $2}' /proc/meminfo | awk '{print $1/1024}')

# Output Summary
echo -e "This freed ${GREEN}$(echo "$free_mem_after - $free_mem_before" | bc) MiB${NC}, so now you have ${GREEN}$free_mem_after MiB${NC} of free RAM."

exit 0
